AlphaWallet/TokenScript

doc/design_paper.md
@colourful-land added a simple introduction to TBML which needs to be edited.
Also a bit too wordy and we can work together on shortening it while still providing the same message.
=> Edit first chapter

doc/design_paper.md
Note: I removed the old first chapter, we can use git history if need be to retrieve it later.
=> edited the next chapter and remove old chapter

doc/design_paper.md
"Just like a house providing a place to live." doesn't make it easier to understand, instead, more confusing, people have to stop here and try to figure out what is the relations between this "house" and token/TBML...
=> remove "Just like a house providing a place to live."

doc/design_paper.md
=> change TMML to TBML

doc/design_paper.md
=> change assiet to asset

doc/design_paper.md
=> change three to four

doc/design_paper.md
change collatoralised to collateralized
=> change collatoralised to collateralized

doc/design_paper.md
change Interoperatibility to Interoperability
=> change Interoperatibility to Interoperability

doc/design_paper.md
=> change Pizaa to Pizza

doc/design_paper.md
change collatorisation to collateralization
=> change collatorisation to collateralization

doc/design_paper.md
=> change satify to satisfy

doc/design_paper.md
change transferrable to transferable
=> change transferrable to transferable

doc/design_paper.md
=> change snipet  to snippet

README.md
Boon guided this round of rennovation of README
=> Tokenscript is the front end of tokens, like Smart Contracts are the back end of tokens

doc/design_paper.md
=> add blank line

doc/design_paper.md
=> Add table of content

examples/ticket/cards/enter.en.shtml
Fix: The action view in the example breaks if the user cancels signing.
=> Make example handle user tapping cancel signing

examples/ticket/Makefile, schema/tokenscript.xsd, schema/xhtml1-strict.xsd, schema/xml.xsd, schema/xmldsig-core-schema.xsd
=> Using xsd files locally

doc/short_paper.md
Wrote on the short version paper. If the long version is outdated (not containing your changes) ignore it.
=> Short Paper

README.md
Please let me know if you feel this version is better than the old.
=> updating README from learnings of EDCON

examples/erc20/DAI.xml, examples/nft/EntryToken.xml, schema/tokenscript.xsd
=> change as and mapping

examples/erc20/DAI.xml
=> Fix for ownerAddress type

schema/tokenscript.xsd
This is useful for validating tsml files.
=> allow XML signature at the tail

examples/erc20/DAI.xml
This PR removes the action which doesn't define how to build a transaction.
If the intent was (and if it's possible) for the action to be provided:
1. Close this PR
2. Add an issue or PR to include the define the transaction
=> Remove spurious xDai-to-Dai action in Dai bridge

examples/erc20/dai-bridge.en.shtml, examples/erc20/shared.css
Changed CSS to render without wrapping and changed input type to number.
=> Changed CSS to render without wrapping and changed input type to number

examples/action/Makefile, examples/erc20/Makefile, examples/nft/Makefile
=> produces .canonicalized.xml.INVALID if validation fails (for debugging)

doc/javascript_api.md, examples/fifa/fifa.xml, schema/tokenscript.xsd
=> remove the IA5String syntax type

examples/action/shared.css, examples/action/xdai-bridge.en.shtml, examples/erc20/dai-bridge.en.shtml, examples/erc20/shared.css
Looks slightly better however it appears that the CSS is not rendering for action only cards @colourful-land 
Edit: was an iOS issue that has been solved
=> with newer design

tutorial/Step 1: Forming the layout.md, tutorial/Step 2: Assembling the XML file.md, tutorial/Step 3: Debugging and testing.md, tutorial/Step 4: Signing and publishing.md
Merge when latest AlphaWallet apps are released.
=> update the tutorial text to match the coming release

doc/getting_started.md
In the spirit of https://facebook.github.io/react-native/docs/getting-started.html.
Started this because I wanted to add the list of implicit attributes and there wasn't an appropriate place.
=> Create 'Getting Started' doc stub

contrib/wizard/erc-templates/erc20/Makefile, contrib/wizard/erc-templates/erc20/approve.en.shtml, contrib/wizard/erc-templates/erc20/erc20.xml, contrib/wizard/erc-templates/erc20/shared.css, contrib/wizard/erc-templates/erc20/transferFrom.en.shtml, contrib/wizard/erc-templates/erc721/Makefile, contrib/wizard/erc-templates/erc721/approve.en.shtml, contrib/wizard/erc-templates/erc721/erc721.xml, contrib/wizard/erc-templates/erc721/shared.css
Adds some basic functionality so that a developer can get up and running quickly with erc20 and erc721 tokens. 
can substitute for https://github.com/AlphaWallet/TokenScript/issues/102
=> add simple example templates for erc721 and erc20

doc/security.md
@James-Sangalli please verify that the public key I provided corresponds to the donation address I provided. If it matches, please update the donation address on README on the top level and approve/merge this.
=> adding a donation address

examples/action/Makefile, examples/erc20/DAI.xml, examples/erc20/Makefile, examples/fifa/Makefile, examples/fifa/fifa.xml, examples/nft/EntryToken.xml, examples/nft/Makefile, schema/README.md, schema/tokenscript.xsd, tutorial/Step 4: Signing and publishing.md
@colourful-land still need arrays, any ideas for the most elegant way? 
For #154
=> add bytes, bytesN, arrays and bool

.gitignore, resources/fast-token-onboarding/README.md, resources/fast-token-onboarding/erc20.canonicalized.xml, resources/fast-token-onboarding/erc721.canonicalized.xml, resources/fast-token-onboarding/sign.sh
Closes https://github.com/AlphaWallet/TokenScript/issues/226
=> Tool for streamlined token onboarding

README.md
=> add one sentence in Why part

examples/edcon/Makefile, examples/edcon/shared.css, examples/edcon/unicon.en.shtml, examples/edcon/unicon.xml
=> WIP add basic edcon draft TokenScript

examples/UEFA/UEFA.xml, examples/UEFA/UEFA.zh.shtml, schema/tokenscript.xsd
Closes #289 
@zhangzhongnan928 do not merge this PR, there is a problem with the view localisation but it is ready for review of the language strings.
If you spot something wrong, leave a comment at the exact line via the github review interface.
=> add Chinese to UEFA

README.md
=> add why XML section

schema/ethereum.xsd, schema/tokenscript.xsd
merge it together with https://github.com/AlphaWallet/TokenScript-Examples/pull/78
=> introducing <ethereum:transaction> based on <ethereum:call>

ERCs/ERC20/ERC20-TokenScript.xml
=> Fix: TokenScript file for ERC20's ownerApproved filter

xmldsig/README.md, xmldsig/js/package.json, xmldsig/js/xmldsigverifier.js
This is taken from the most reasonable case produced in the lengthy study published here https://community.tokenscript.org/t/the-confusing-current-status-of-various-webcrypto-api-providers/393
=> adding JavaScript xmldsig verification example

ERCs/ERC20/ERC20-TokenScript.xml, ERCs/ERC721/ERC721-TokenScript.xml, schema/asnx.xsd
1. merge this together with https://github.com/AlphaWallet/TokenScript-Examples/pull/93
2. Don't merge this in until both αW can handle the new schema.
=> RFC4912 required a <type> for a named type that defines a type

schema/tokenscript.xsd
Rational:
https://community.tokenscript.org/t/cards-name/406
No change needed in iOS/Android to make this work, so this one can be merged without waiting for a supportive release.
Merge this together with the other
https://github.com/AlphaWallet/TokenScript-Examples/pull/119
=> making name="…" mandantory in cards

schema/tokenscript.xsd
https://github.com/AlphaWallet/TokenScript/blob/2bc5140585cb0ff2115cdf5fe001ec5ab256797c/schema/tokenscript.xsd#L62
=> allowing 'select' on `ethereum:call`

schema/tokenscript.xsd
http://community.tokenscript.org/t/weekly-design-meeting-21/329
=> introducing distinct as per previous ts meeting
