AlphaWallet/TokenScript

- doc/javascript_api.md
- examples/ticket/js/generalized-time-test.html
- examples/ticket/js/generalized-time.js
@hboon @JamesSmartCell notice the change in Date. I didn't change the buggy design which causes a zoned date-time to drift with the user's device, which is:
1. If the user has a local time of 11 pm Sydney and the FIFA match is at Mosco time of 5 pm, the user's mobile phone displays the time of the match at 5 pm, which is internally stored as 5pm Sydney (6am UTC+0) since Javascript internally try to keep time unambiguous.
2. The user takes off.
3. The user lands in Mosco. The mobile phone updates the time and the ticket says the FIFA match starts at 9 am (6 am UTC+3).
@hboon is of the opinion that this can be amended by having react framework to send an update to refresh the FIFA start time as 5 pm Mosco (5pm UTC+3). But that means:
- When timezone changes, the react framework need to send …
> javascript api doc

- examples/ticket/cards/enter.en.shtml
- examples/ticket/cards/token.en.shtml
Changes:
1. Introduce JavaScript functions in the example to format BinaryTime into date and time, separately. (it reads from `this.props.time.date` instead of `this.props.time.venue`).
2. Call `web3.tokens.dataChanged()` instead of `refresh()`
---
@JamesSmartCell: the Android TokenScript client will need to make the following changes:
1. Generally for datetime(s), instead of generating `GeneralizedTime` as a dictionary with the keys `venue` and `locale`, you'll have to generate them with the keys `generalizedTime` and `date` [1]:
```
time: {
generalizedTime: "19851106210627-0500",
date: new Date("1985-11-07T02:06:27")
}
```
For our door token example, since the `time` attribute is BinaryTime, we omit the `generalizedTime` key and generate it like this:
```
time: {
date: new …
```
> Tweak JavaScript in example to use TokenScript dataChanged() callback and render BinaryTime

- examples/ticket/cards/enter.en.shtml
@JamesSmartCell required change in the TokenScript client for Android.
Originally, you'd have something like this:
```
return """
const addressHex = "\(address.description.lowercased())"
const rpcURL = "\(server.rpcURL.absoluteString)"
const chainID = "\(server.chainID)"
function executeCallback (id, error, value) {
AlphaWallet.executeCallback(id, error, value)
}
AlphaWallet.init(rpcURL, {
getAccounts: function (cb) { cb(null, [addressHex]) },
processTransaction: function (tx, cb){
console.log('signing a transaction', tx)
const { id = 8888 } = tx
AlphaWallet.addCallback(id, cb)
webkit.messageHandlers.signTransaction.postMessage({"name": "signTransaction", "object":     tx, id: id})
},
signMessage: function (msgParams, cb) {
const { data } = msgParams
const { id = 8888 } = msgParams …
```
> Tweak Javascript/HTML in example sign challenge as personal message and close screen after sending response successfully

- examples/ticket/cards/token.en.shtml
@JamesSmartCell if the `time` attribute is already generated as a dictionary with `date` and `generalizedTime` key-value pairs, this should just work and display as 5pm.
You can see examples of why CDATAs are useful here. This PR uses code that includes < and &. In order to work without CDATAs, I modified them to be entities like `&lt;` and `&amp;`. Let's just leave it like this for the moment and we can revisit why it doesn't work when we have the time. (but useful to know in case this comes up during the workshop)
> Tweak Javascript in example to display as GeneralizedTime instead

- examples/ticket/cards/shared.css
Remove the standard fonts from shared styles, which should be injected directly by the app.
Implementation-wise, instead of doing:
```
return """
\(sharedStyles)
\(sanitizedHtml)
"""
```
do:
```
return """
\(standardFontStyles)
\(sharedStyles)
\(sanitizedHtml)
"""
```
The iOS version injects something like this (for each `@font-face`) as standardFontStyles:
```
<style type="text/css">
@font-face {
font-family: 'SourceSansPro';
src: url('\(Constants.tokenScriptUrlSchemeForResources)SourceSansPro-Light.otf') format('opentype');
font-weight: lighter;
}
...
</style>
```
This is because the path to access the fonts should/would not be exposed to the TokenScript authors. In the future, we might consider renaming the font family to something along the lines of "Standard" or "System".
> Remove standard fonts from shared styles in example

- examples/ticket/Makefile
- examples/ticket/cards/token.en.shtml
Solves Boon's issue #88 with the minimum change to his code. Since he already used html entity over CDATA in a few places, I can't just re-introduce `CDATA` overall, but instead, I segmented `<script>` into 2, one use CDATA and the other not. @hboon please do local testing before merging as I don't have the test environment.
> fix make error by introducing CDATA

- examples/ticket/cards/shared.css
- examples/ticket/cards/token.en.shtml
* Modify styles to that we use SourceSansPro instead of mixing Roboto. Our native apps only uses SourceSansPro.
* Also restore styles so that they look close to our ticket layout
* Tweak margins in first line to separate count and name
Looks like this (like our tickets):
> Tweak styles in example to use standard font used in mobile app

- examples/dai/Makefile
- examples/dai/dai.xml
- schema/tokenscript.xsd
The new schema has these features 𝑛𝑒𝑒𝑑𝑒𝑑 in supporting DAI
1. introduces `<string>` and `<plurals>` element in `<name>`, for localising complex strings.
2. introduces `name="xxx"` attribute for `<contract>` to allow more than 1 contracts.
3. introduces `<origins>` element to contain origins of tokens and attribute-types, in solving #115
4. introduce `<user-entry>` element to contain attribute value sourced from user's entry.
5. replace `<origin function="xxx">` with `<etherem function="xx"`
6. replace `<origin bitmask="xxx">` with `<token-id bitmask="xxx"`
7. introduce `<transaction>` in `<action>`
8. allow `<attribute-type>` in `<action>`
9. use `e18` to solve #116
Given the number of changes we need to do in this sprint (verifying signature, using the new repo server) I feel we should …
> Dai+schema 2019/05

- examples/erc20/dai-bridge.en.shtml
Before applying this PR, the DAI example:
* computed the balance wrongly (used `10e18`. Should be `1e18`)
* couldn't display the balance because the data may not be immediately available upon the first time it's rendered
> Fix: make DAI example display DAI balance correctly

- doc/design_paper.md
I feel that:
People won't agree with the "the blockchain has two primary functions:
It provides a frictionless market.
It integrates the web." directly.
But most of them agree that "blockchain is replacing the trusted third parties".
I think it is better to say that the 2 functions are coming from "blockchain is replacing the trusted third parties" instead of introducing the 2 functions directly.
@colourful-land what do you think?
> add "replacing trusted third party" before explaining tokenisation 

- examples/action/Makefile
- examples/action/XDAI-bridge.xml
- examples/action/XDAI.xml
- examples/erc20/DAI.xml
- schema/tokenscript.xsd
Before reading the changes, get familiar with the term I invented. I call changing the definition of existing elements or attributes with a new pull request to a tokenscript 𝑑𝑟𝑖𝑓𝑡𝑖𝑛𝑔. Schema changes should be of its own PR at a monthly interval.
The changes from the previous one demonstrated to you guys were:
1. `<exclude>` rules are excluded here because it begets some schema drifting and it made the target bigger.
2. change in `<token>` element:
````
<ts:input>
<ts:token name="xdai">
<ts:currency network="100"/>
</ts:token>
</ts:input>
````
has become:
````
<ts:input>
<ts:token name="xdai">
<ts:ethereum network="100"/>
</ts:token>
</ts:input>
````
Because I intend to make stuff specific to Ethereum with an element that has `ethereum` keyword. The same change, in the same spirit, should …
> Xdai bridge action

- examples/action/XDAI-bridge.xml
- schema/tokenscript.xsd
the <name> tag inconsistency is fixed by updating schema.
In all other tokenscript the action name is defined similar to this:
<ts:name>
<ts:string xml:lang="en">Enter</ts:string>
<ts:string xml:lang="zh">入場</ts:string>
<ts:string xml:lang="es">Entrar</ts:string>
</ts:name>
Whereas here it's:
<ts:name>Transfer xDAI to DAI</ts:name>
Replaced with something like this
<ts:name>
<ts:string xml:lang="en">Convert xAW to awDai</ts:string>
</ts:name>
> forbid the use of <name> without sub-elements

- examples/action/XDAI-bridge.xml
This PR changes it to "Transfer to DAI".
Screenshot below is generated with a recent commit to the TokenScript branch which adds some left and right margin to long titles:
> Shorten title for action of xDai bridge

- examples/action/xdai-bridge.en.shtml
`<input>` needs an `id` matching the attribute so TokenScript client is able to retrieve it.
> Fix: xDai bridge to retrieve amount entered

- doc/security.md
This pull request can stay for a week or two until we are sure of it.
My question: which one is more important, consistency or simplicity?
If you choose simplicity, the express-of-trust address should be created from the hash of the TokenScript file. This is the simplest a noob programmer can do and he can do so with keccak without touching outlandish† hash methods like SHA256
† outlandish - to the eyes of someone who learned nothing else about cryptography except those used in Ethereum
If you choose consistency, the express-of-trust address should be created from the digest of the canonicalized root element of the TokenScript. The downside is that the hash method has to be agreed on before (can't be keccak because XMLSIG doesn't support it), so we fixed it to SHA256. The upside is that …
> 𝑐𝑜𝑛𝑡𝑟𝑜𝑣𝑒𝑟𝑠𝑦: using the Digest instead of file hash for express-of-trust

- schema/ethereum.xsd
- schema/tokenscript.xsd
in all cards, all references to ethereum events and calls are reällocated to the ethereum namespace
detail: http://tokenscript.org/2020/06/tokenscript#ethereum-namespace
This needs to be merged in at the same time as https://github.com/AlphaWallet/TokenScript-Examples/pull/73
> moving etheruem calls to its own namespace

- schema/tokenscript.xsd
this should be the last missing item in schema/06
merge with https://github.com/AlphaWallet/TokenScript-Examples/pull/79
> moving attributes' type definition into its own element

- schema/asnx.xsd
- schema/ethereum.xsd
- schema/tokenscript.xsd
This goes with https://github.com/AlphaWallet/TokenScript-Examples/pull/84
1. `<selection id=` becomes `<selection name=`
2. ASN modules usage corrected to align with RFC4912.
> Id and asnx module correction

- ERCs/ERC20/ERC20-TokenScript.xml
- ERCs/ERC721/ERC721-TokenScript.xml
The new default TS files are valid:
````
weiwu@damascus:~/IdeaProjects/TokenScript/ERCs$ TOKENSCRIPT_SCHEMA=/home/weiwu/IdeaProjects/TokenScript/schema/tokenscript.xsd ../examples/validate.sh ERC20/ERC20-TokenScript.xml 
ERC20-TokenScript.canonicalized.xml validates
[Valid]   : ERC20/ERC20-TokenScript.xml
weiwu@damascus:~/IdeaProjects/TokenScript/ERCs$ TOKENSCRIPT_SCHEMA=/home/weiwu/IdeaProjects/TokenScript/schema/tokenscript.xsd ../examples/validate.sh ERC721/ERC721-TokenScript.xml 
ERC721-TokenScript.canonicalized.xml validates
[Valid]   : ERC721/ERC721-TokenScript.xml
````
> allowing contracts to be absent  in ethereum:*

- ERCs/ERC20/ERC20-TokenScript.xml
- ERCs/ERC721/ERC721-TokenScript.xml
- doc/javascript_api.md
- schema/asnx.xsd
- schema/ethereum.xsd
- schema/tokenscript.xsd
As per TokenScript weekly meeting #40, developers should base their Activity A3 project on the files provided in ERCs directory. Notice that this is based on PR #365 which will be merged in a few weeks since αW is released with [a fix](https://github.com/AlphaWallet/alpha-wallet-android/pull/1484)
> Add origins in activity
